### PR TITLE
Added in parameter support, re-enabled policies

### PR DESCRIPTION
**Pull request by brettminnie**
For rabbit 3.8.x policies require the latest version of ansible 2.9

### CODE REVIEW

**Comment by rockandska** [comment]
Hi,

Thanks for the PR and catch that the tasks for policies were not included at all !
The tests failing because of the erlang series not compatible with new rabbitmq 3.7 and need to fix that before and will eventually ask you to rebase.

**Comment by brettminnie** [comment]
Great no problem. Let me know when you want the rebase and I'll make it so

B

**Comment by flora-five** [comment]
While I was working on adding support for global parameters, I've noticed that the implementation to delete unwanted parameters is incorrect.

I've made a fix for that in my https://github.com/flora-five/ansible-role-rabbitmq/commits/parameters branch. There is also a commit to update tasks/pre_checks.yml.

@brettminnie could you check the issue and my proposed changes? Thank you!

**Comment by brettminnie** [comment]
@flora-five @rockandska  is the owner of the repo, I merely was hitting it with a stick 😄

**Comment by flora-five** [comment]
Thanks @brettminnie ! I've mentioned you as the author of this PR, if you would like to commit them into your branch and add them to this PR.

**Comment by brettminnie** [comment]
Cool I'll get it sorted out tomorrow ! :+1:

**Comment by rockandska** [comment]
Hi @brettminnie / @flora-five 

Just to let you know that i'm working on fixing tests before merging the PR you submitted.
I will not add support for Rabbitmq 3.8 right now because I need to fix the actual automatic cluster configuration since it fails with [Erlang 22](https://github.com/erlang/otp/pull/2170)

Regards,

**Comment by rockandska** [comment]
Closed in #28 

Sorry for the delay and thanks for the PR

**Pull request closed without merging**
